import random

def dividir_en_equipos(personas, num_equipos):
    random.shuffle(personas)
    equipos = [[] for _ in range(num_equipos)]
    
    for i, persona in enumerate(personas):
        equipos[i % num_equipos].append(persona)
    
    return equipos
personas = ["Prudencio Montalvo Mario Axel",
"Martínez Rodríguez Edwin Roberto", 
"Pizarro Lagunas Alonso Darío",
"Martínez Cortés Bryan Eduardo",
"Juárez luna Pascual Enrique",
"Burciaga Piña Erick Osvaldo",
"Alejandro Sosa Murguía",
"López Robles Jimena",
"Martell Enríquez Raúl",
"Magdaleno Flores Nilton Sebastian",
"Díaz Sánchez David",
"Jiménez Apodaca Josué",
"Arellano Ortiz Andre",
"Galan Olivares Juan Miguel",
"Rodriguez Flores Aldo Alberto",
"Magaña Celis David",
"Ramírez Reyes Alfonso",
"Miguel de la Torre Myrna", 
"Rico Valdez Silvia",
"Dafne Elizabeth Zepeda Gonzalez",
"José de Jesús Vega Vázquez",
"Contreras Morales Luis Antonio",
"Galindo Muciño Roberto",
"Mauro Hernández José Mario", 
"Alexia Abigail Martínez Gómez",
"Rigoberto Canseco Lopez",
"Guzmán Núñez Irving Ricardo", 
"Cruz Mercado Omar Rodrigo", 
"Velazquez Perez Marlenne",
"Álamo Díaz Luis Manuel", ]
Practica 1
practica_1 = dividir_en_equipos(personas,7)
practica_1
[['Pizarro Lagunas Alonso Darío',
  'Arellano Ortiz Andre',
  'Galan Olivares Juan Miguel',
  'Rico Valdez Silvia',
  'Rigoberto Canseco Lopez'],
 ['Velazquez Perez Marlenne',
  'Dafne Elizabeth Zepeda Gonzalez',
  'Burciaga Piña Erick Osvaldo',
  'Guzmán Núñez Irving Ricardo',
  'Galindo Muciño Roberto'],
 ['Alejandro Sosa Murguía',
  'Alexia Abigail Martínez Gómez',
  'Magdaleno Flores Nilton Sebastian',
  'Cruz Mercado Omar Rodrigo'],
 ['Miguel de la Torre Myrna',
  'Ramírez Reyes Alfonso',
  'Contreras Morales Luis Antonio',
  'Martínez Rodríguez Edwin Roberto'],
 ['Rodriguez Flores Aldo Alberto',
  'López Robles Jimena',
  'Jiménez Apodaca Josué',
  'Prudencio Montalvo Mario Axel'],
 ['Martell Enríquez Raúl',
  'Magaña Celis David',
  'Álamo Díaz Luis Manuel',
  'Díaz Sánchez David'],
 ['Juárez luna Pascual Enrique',
  'José de Jesús Vega Vázquez',
  'Martínez Cortés Bryan Eduardo',
  'Mauro Hernández José Mario']]
Practica 2
practica_2 = dividir_en_equipos(personas,7)
practica_2
[['Rigoberto Canseco Lopez',
  'Martínez Rodríguez Edwin Roberto',
  'Pizarro Lagunas Alonso Darío',
  'Jiménez Apodaca Josué',
  'Martínez Cortés Bryan Eduardo'],
 ['Prudencio Montalvo Mario Axel',
  'Juárez luna Pascual Enrique',
  'Burciaga Piña Erick Osvaldo',
  'Ramírez Reyes Alfonso',
  'Guzmán Núñez Irving Ricardo'],
 ['Velazquez Perez Marlenne',
  'Dafne Elizabeth Zepeda Gonzalez',
  'Magdaleno Flores Nilton Sebastian',
  'Díaz Sánchez David'],
 ['José de Jesús Vega Vázquez',
  'Arellano Ortiz Andre',
  'Magaña Celis David',
  'Cruz Mercado Omar Rodrigo'],
 ['Contreras Morales Luis Antonio',
  'Miguel de la Torre Myrna',
  'Galan Olivares Juan Miguel',
  'Mauro Hernández José Mario'],
 ['Rico Valdez Silvia',
  'López Robles Jimena',
  'Alejandro Sosa Murguía',
  'Rodriguez Flores Aldo Alberto'],
 ['Álamo Díaz Luis Manuel',
  'Alexia Abigail Martínez Gómez',
  'Martell Enríquez Raúl',
  'Galindo Muciño Roberto']]
Practica 3
practica_3 = dividir_en_equipos(personas,7)
practica_3  
[['Alexia Abigail Martínez Gómez',
  'Velazquez Perez Marlenne',
  'Juárez luna Pascual Enrique',
  'José de Jesús Vega Vázquez',
  'López Robles Jimena'],
 ['Dafne Elizabeth Zepeda Gonzalez',
  'Miguel de la Torre Myrna',
  'Prudencio Montalvo Mario Axel',
  'Cruz Mercado Omar Rodrigo',
  'Alejandro Sosa Murguía'],
 ['Jiménez Apodaca Josué',
  'Martell Enríquez Raúl',
  'Guzmán Núñez Irving Ricardo',
  'Martínez Rodríguez Edwin Roberto'],
 ['Magdaleno Flores Nilton Sebastian',
  'Magaña Celis David',
  'Rico Valdez Silvia',
  'Arellano Ortiz Andre'],
 ['Álamo Díaz Luis Manuel',
  'Mauro Hernández José Mario',
  'Contreras Morales Luis Antonio',
  'Galan Olivares Juan Miguel'],
 ['Rodriguez Flores Aldo Alberto',
  'Díaz Sánchez David',
  'Ramírez Reyes Alfonso',
  'Martínez Cortés Bryan Eduardo'],
 ['Burciaga Piña Erick Osvaldo',
  'Rigoberto Canseco Lopez',
  'Galindo Muciño Roberto',
  'Pizarro Lagunas Alonso Darío']]

Practica 4
practica_4 = dividir_en_equipos(personas,7)
practica_4
[['Mauro Hernández José Mario',
  'Díaz Sánchez David',
  'Juárez luna Pascual Enrique',
  'Burciaga Piña Erick Osvaldo',
  'Álamo Díaz Luis Manuel'],
 ['Galindo Muciño Roberto',
  'Miguel de la Torre Myrna',
  'Guzmán Núñez Irving Ricardo',
  'Ramírez Reyes Alfonso',
  'Cruz Mercado Omar Rodrigo'],
 ['Jiménez Apodaca Josué',
  'Magdaleno Flores Nilton Sebastian',
  'Arellano Ortiz Andre',
  'Rodriguez Flores Aldo Alberto'],
 ['Dafne Elizabeth Zepeda Gonzalez',
  'Pizarro Lagunas Alonso Darío',
  'Martínez Cortés Bryan Eduardo',
  'Alexia Abigail Martínez Gómez'],
 ['Galan Olivares Juan Miguel',
  'Magaña Celis David',
  'López Robles Jimena',
  'Rigoberto Canseco Lopez'],
 ['Alejandro Sosa Murguía',
  'José de Jesús Vega Vázquez',
  'Rico Valdez Silvia',
  'Martell Enríquez Raúl'],
 ['Contreras Morales Luis Antonio',
  'Velazquez Perez Marlenne',
  'Prudencio Montalvo Mario Axel',
  'Martínez Rodríguez Edwin Roberto']]